modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "hexvoid"
version = "${version}"
displayName = "HexVoid"
authors = "Meoyuta"
description = '''
An extension mod for Hex Casting
'''
#logoFile = ""

[[dependencies.hexvoid]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexvoid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexvoid]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
